from app.tools.contracts import ToolRisk, ToolSpec


TOOL_SPECS: tuple[ToolSpec, ...] = (
    ToolSpec(
        name="search_patient",
        risk=ToolRisk.READ,
        required_permission="patients:read",
    ),
    ToolSpec(
        name="get_patient_appointments",
        risk=ToolRisk.READ,
        required_permission="appointments:read",
    ),
    ToolSpec(
        name="search_clinics",
        risk=ToolRisk.READ,
        required_permission="clinics:read",
    ),
    ToolSpec(
        name="get_clinic_information",
        risk=ToolRisk.READ,
        required_permission="clinics:read",
    ),
    ToolSpec(
        name="search_services",
        risk=ToolRisk.READ,
        required_permission="services:read",
    ),
    ToolSpec(
        name="get_service_information",
        risk=ToolRisk.READ,
        required_permission="services:read",
    ),
    ToolSpec(
        name="search_doctors",
        risk=ToolRisk.READ,
        required_permission="doctors:read",
    ),
    ToolSpec(
        name="get_available_slots",
        risk=ToolRisk.READ,
        required_permission="appointments:read",
    ),
    ToolSpec(
        name="create_appointment",
        risk=ToolRisk.MUTATION,
        required_permission="appointments:create",
        requires_confirmation=True,
        requires_idempotency=True,
    ),
    ToolSpec(
        name="reschedule_appointment",
        risk=ToolRisk.SENSITIVE_MUTATION,
        required_permission="appointments:update",
        requires_confirmation=True,
        requires_idempotency=True,
    ),
    ToolSpec(
        name="cancel_appointment",
        risk=ToolRisk.SENSITIVE_MUTATION,
        required_permission="appointments:cancel",
        requires_confirmation=True,
        requires_idempotency=True,
    ),
    ToolSpec(
        name="confirm_appointment",
        risk=ToolRisk.MUTATION,
        required_permission="appointments:confirm",
        requires_confirmation=True,
        requires_idempotency=True,
    ),
    ToolSpec(
        name="create_crm_lead",
        risk=ToolRisk.MUTATION,
        required_permission="crm:create",
        requires_idempotency=True,
    ),
    ToolSpec(
        name="update_crm_contact",
        risk=ToolRisk.SENSITIVE_MUTATION,
        required_permission="crm:update",
        requires_confirmation=True,
        requires_idempotency=True,
    ),
    ToolSpec(
        name="create_callback",
        risk=ToolRisk.MUTATION,
        required_permission="callbacks:create",
        requires_idempotency=True,
    ),
    ToolSpec(
        name="create_complaint",
        risk=ToolRisk.MUTATION,
        required_permission="complaints:create",
        requires_idempotency=True,
    ),
    ToolSpec(
        name="send_sms",
        risk=ToolRisk.MUTATION,
        required_permission="notifications:send",
        requires_idempotency=True,
    ),
    ToolSpec(
        name="send_notification",
        risk=ToolRisk.MUTATION,
        required_permission="notifications:send",
        requires_idempotency=True,
    ),
    ToolSpec(
        name="transfer_to_operator",
        risk=ToolRisk.MUTATION,
        required_permission="handoff:create",
        requires_idempotency=True,
    ),
    ToolSpec(
        name="get_approved_knowledge",
        risk=ToolRisk.READ,
        required_permission="knowledge:read",
    ),
)


TOOL_SPECS_BY_NAME: dict[str, ToolSpec] = {spec.name: spec for spec in TOOL_SPECS}
